(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.ssMetadata = [
		{name:"index_atlas_", frames: [[0,881,1204,224],[649,0,647,879],[1206,881,223,48],[0,0,647,879],[1298,0,100,96]]}
];


// symbols:



(lib.bbg = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.FlashAICB = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.FlashAICB_1 = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.FlashAICB_2 = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.Image = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Tween22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AcrBYQgKgDgHgHQgIgHgDgJQgEgIAAgMIAAhcIAXAAIAABbQAAAGACAGQACAFADADQAEAEAGACQAFACAIAAQAHAAAGgCQAGgCADgEQAEgDACgFQACgGAAgGIAAhbIAXAAIAABcQAAAMgEAIQgEAJgHAHQgHAHgKADQgJADgMAAQgMAAgJgDgAX0BGQgVgVAAgeQAAgIACgHQABgGACgGIAHgNIAJgLQAGgFAGgEIAMgHIANgEIAPgBIAOABIAOAEIAMAHQAGAEAFAFIAKALIAGANIAEAMIABAPIgBAOIgEAOIgGAMQgEAGgGAFQgFAGgGAEIgMAGIgOAEIgOABQgeAAgWgVgAYEgQQgHAHgDAJQgEAIAAALQAAAKAEAKQADAJAHAHQAIAHAJADQAIAEALAAQAKAAAJgEQAJgDAHgHQAOgPAAgVQAAgLgDgIQgEgJgHgHQgHgHgJgEQgJgDgKAAQgVAAgPAOgAThBZQgJgCgHgFQgHgEgFgHQgFgGgDgIIAUgMQACAGADAFQAEAEAEADQAEADAGABQAFACAHAAIALgBQAFgCAEgCQADgCABgEQACgDAAgEQAAgFgCgDQgCgDgDgCQgHgFgSgFIgQgGIgNgHQgHgFgDgHQgEgGAAgJQAAgTANgLQAHgFAIgDQAIgDAJAAQAIAAAIACQAHACAHAEQAGAEAFAGQAFAGADAHIgTALIgGgIQgCgEgEgCQgEgDgEgBIgKgBIgJABQgEABgDACIgEAGIgCAHQAAAEACADIAEAFQAMAFAKAEIAWAIQAHACAEADQAGAGAEAGIADAIQABAEAAAFQAAAKgEAHQgDAIgHAFQgHAGgJADQgIACgMAAQgKAAgIgCgAIYBGQgVgVAAgeQAAgIACgHQABgGACgGIAHgNIAJgLQAGgFAGgEIAMgHIANgEIAPgBIAOABIAOAEIAMAHQAGAEAFAFIAKALIAGANIAEAMIABAPIgBAOIgEAOIgGAMQgEAGgGAFQgFAGgGAEIgMAGIgOAEIgOABQgeAAgWgVgAIogQQgHAHgDAJQgEAIAAALQAAAKAEAKQADAJAHAHQAIAHAJADQAIAEALAAQAKAAAJgEQAJgDAHgHQAOgPAAgVQAAgLgDgIQgEgJgHgHQgHgHgJgEQgJgDgKAAQgVAAgPAOgAGyBZQgJgCgGgFQgHgEgFgHQgFgGgDgIIAUgMQACAGADAFQADAEAFADQAEADAFABQAGACAGAAIAMgBQAFgCADgCQADgCACgEQABgDAAgEQAAgFgBgDQgCgDgEgCQgHgFgRgFIgRgGIgNgHQgHgFgDgHQgDgGAAgJQAAgTANgLQAGgFAIgDQAIgDAKAAQAIAAAHACQAIACAGAEQAGAEAFAGQAFAGADAHIgTALIgFgIQgDgEgEgCQgDgDgFgBIgJgBIgJABQgFABgCACIgFAGIgBAHQAAAEABADIAFAFQALAFALAEIAWAIQAGACAEADQAHAGADAGIAEAIQABAEgBAFQAAAKgDAHQgDAIgHAFQgHAGgJADQgJACgLAAQgKAAgJgCgAB5BYQgKgDgHgHQgIgHgDgJQgEgIAAgMIAAhcIAXAAIAABbQAAAGACAGQACAFADADQAEAEAGACQAFACAIAAQAHAAAGgCQAGgCADgEQAEgDACgFQACgGAAgGIAAhbIAXAAIAABcQAAAMgEAIQgEAJgHAHQgHAHgKADQgJADgMAAQgMAAgJgDgAi9BGQgVgVAAgeQAAgIACgHQABgGACgGIAHgNIAJgLQAGgFAGgEIAMgHIANgEIAPgBIAOABIAOAEIAMAHQAGAEAFAFIAKALIAGANIAEAMIABAPIgBAOIgEAOIgGAMQgEAGgGAFQgFAGgGAEIgMAGIgOAEIgOABQgeAAgWgVgAitgQQgHAHgDAJQgEAIAAALQAAAKAEAKQADAJAHAHQAIAHAJADQAIAEALAAQAKAAAJgEQAJgDAHgHQAOgPAAgVQAAgLgDgIQgEgJgHgHQgHgHgJgEQgJgDgKAAQgVAAgPAOgAoNBYQgJgDgIgHQgHgHgEgJQgEgIAAgMIAAhcIAXAAIAABbQAAAGACAGQACAFAEADQAEAEAFACQAGACAHAAQAIAAAFgCQAGgCAEgEQAEgDACgFQABgGAAgGIAAhbIAXAAIAABcQAAAMgDAIQgEAJgHAHQgIAHgJADQgKADgMAAQgLAAgKgDgAt4BYQgJgDgIgHQgHgHgEgJQgEgIAAgMIAAhcIAXAAIAABbQAAAGACAGQACAFAEADQAEAEAFACQAGACAHAAQAIAAAFgCQAGgCAEgEQAEgDACgFQABgGAAgGIAAhbIAXAAIAABcQAAAMgDAIQgEAJgHAHQgIAHgJADQgKADgMAAQgLAAgKgDgAyqBaIgOgEIgMgGIgLgJQgGgGgDgGIgHgMQgDgGgBgHQgBgIAAgHQAAgIABgHQABgGADgHIAHgMQADgGAGgFQAFgFAGgEQAFgEAHgDIAOgEIAPgBQAJAAAJADQAJACAIAEQAIAEAGAHQAHAGAEAIIgUALIgHgJQgEgEgFgDQgFgDgGgCIgNgBQgLAAgJADQgJAEgHAHQgOAOAAAVQAAAWAOAOQAHAHAJADQAJAEALAAIANgCQAGgBAFgDQAFgDAEgEIAHgKIAUAMQgEAHgGAHQgHAGgIAEQgIAFgJACQgIACgKAAIgPgBgA7GBYQgKgDgHgHQgIgHgDgJQgEgIAAgMIAAhcIAXAAIAABbQAAAGACAGQACAFADADQAEAEAGACQAFACAIAAQAHAAAGgCQAGgCADgEQAEgDACgFQACgGAAgGIAAhbIAXAAIAABcQAAAMgEAIQgEAJgHAHQgHAHgKADQgJADgMAAQgMAAgJgDgAbeBZIhCheIAABeIgXAAIAAiLIASAAIBCBeIAAheIAXAAIAACLgAWQBZIAAg4IgxhTIAaAAIAiA9IAig9IAaAAIgwBTIAAA4gAU5BZIAAiLIAXAAIAACLgASaBZIgegzIgbAAIAAAzIgXAAIAAiLIA4AAQATAAANANQANANAAATQAAAFgCAHQgCAGgDAFQgEAGgFAEQgFAEgHACIAgA3gARhARIAhAAQAFAAAEgCQAEgBADgEQADgDABgEQACgDAAgFQAAgFgCgEQgBgFgDgDQgDgDgEgCQgEgCgFAAIghAAgAPhBZIAAiLIBUAAIAAAWIg9AAIAAAjIA4AAIAAAWIg4AAIAAAmIA+AAIAAAWgAOGBZIgxiLIAZAAIAmBvIAlhvIAZAAIgxCLgAMCBZIhCheIAABeIgXAAIAAiLIASAAIBCBeIAAheIAXAAIAACLgAE2BZIhCheIAABeIgXAAIAAiLIASAAIBCBeIAAheIAXAAIAACLgAAsBZIhBheIAABeIgXAAIAAiLIASAAIBBBeIAAheIAXAAIAACLgAj1BZIg3hDIAABDIgXAAIAAiLIAXAAIAAA+IA1g+IAbAAIg4BDIA6BIgAl2BZIAAiLIAXAAIAACLgAqMBZIAAiLIAXAAIAAB1IA5AAIAAAWgAq6BZIhCheIAABeIgXAAIAAiLIASAAIBCBeIAAheIAXAAIAACLgAvwBZIgKgcIg7AAIgKAcIgZAAIAziLIAbAAIAzCLgAwBAnIgXg+IgWA+IAtAAgA0FBZIgKgcIg7AAIgKAcIgZAAIAziLIAbAAIAzCLgA0WAnIgXg+IgWA+IAtAAgA23BZIAAg4IgxhTIAaAAIAjA9IAig9IAaAAIgxBTIAAA4gA4JBZIhCheIAABeIgXAAIAAiLIASAAIBCBeIAAheIAXAAIAACLgA90BZIAAiLIA3AAIAOABIANAEQAGACAFAEIAKAJQATAUAAAdQAAAdgTAVIgKAIQgFAEgGADQgGACgHABIgOACgA9dBDIAgAAQAKAAAIgEQAIgDAGgHQAHgHADgIQADgJAAgKQAAgLgDgIQgDgIgHgHQgGgGgIgEQgIgDgKAAIggAAgAnthBQgEgEAAgFQAAgFAEgDQADgEAFAAQAFAAAEAEQADADAAAFQAAAFgDAEQgEADgFAAQgFAAgDgDgAoThBQgEgEAAgFQAAgFAEgDQADgEAFAAQAFAAAEAEQADADAAAFQAAAFgDAEQgEADgFAAQgFAAgDgDgAtYhBQgEgEAAgFQAAgFAEgDQADgEAFAAQAFAAAEAEQADADAAAFQAAAFgDAEQgEADgFAAQgFAAgDgDgAt+hBQgEgEAAgFQAAgFAEgDQADgEAFAAQAFAAAEAEQADADAAAFQAAAFgDAEQgEADgFAAQgFAAgDgDgA6nhBQgDgEAAgFQAAgFADgDQAEgEAFAAQAFAAADAEQAEADAAAFQAAAFgEAEQgDADgFAAQgFAAgEgDgA7NhBQgDgEAAgFQAAgFADgDQAEgEAFAAQAFAAADAEQAEADAAAFQAAAFgEAEQgDADgFAAQgFAAgEgDgAU/g/QgEgCgCgDQgDgEAAgEQAAgFAFgFQAEgEAFAAQAFAAADADQAEACABAEQACAEgBAEQgBAEgDADQgDADgEABIgCAAIgGgBgAlwg/QgEgCgCgDQgDgEAAgEQAAgFAFgFQAEgEAFAAQAFAAADADQAEACABAEQACAEgBAEQgBAEgDADQgDADgEABIgCAAIgGgBg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-190.8,-9.1,381.8,18.2);


(lib.Tween21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AcrBYQgKgDgHgHQgIgHgDgJQgEgIAAgMIAAhcIAXAAIAABbQAAAGACAGQACAFADADQAEAEAGACQAFACAIAAQAHAAAGgCQAGgCADgEQAEgDACgFQACgGAAgGIAAhbIAXAAIAABcQAAAMgEAIQgEAJgHAHQgHAHgKADQgJADgMAAQgMAAgJgDgAX0BGQgVgVAAgeQAAgIACgHQABgGACgGIAHgNIAJgLQAGgFAGgEIAMgHIANgEIAPgBIAOABIAOAEIAMAHQAGAEAFAFIAKALIAGANIAEAMIABAPIgBAOIgEAOIgGAMQgEAGgGAFQgFAGgGAEIgMAGIgOAEIgOABQgeAAgWgVgAYEgQQgHAHgDAJQgEAIAAALQAAAKAEAKQADAJAHAHQAIAHAJADQAIAEALAAQAKAAAJgEQAJgDAHgHQAOgPAAgVQAAgLgDgIQgEgJgHgHQgHgHgJgEQgJgDgKAAQgVAAgPAOgAThBZQgJgCgHgFQgHgEgFgHQgFgGgDgIIAUgMQACAGADAFQAEAEAEADQAEADAGABQAFACAHAAIALgBQAFgCAEgCQADgCABgEQACgDAAgEQAAgFgCgDQgCgDgDgCQgHgFgSgFIgQgGIgNgHQgHgFgDgHQgEgGAAgJQAAgTANgLQAHgFAIgDQAIgDAJAAQAIAAAIACQAHACAHAEQAGAEAFAGQAFAGADAHIgTALIgGgIQgCgEgEgCQgEgDgEgBIgKgBIgJABQgEABgDACIgEAGIgCAHQAAAEACADIAEAFQAMAFAKAEIAWAIQAHACAEADQAGAGAEAGIADAIQABAEAAAFQAAAKgEAHQgDAIgHAFQgHAGgJADQgIACgMAAQgKAAgIgCgAIYBGQgVgVAAgeQAAgIACgHQABgGACgGIAHgNIAJgLQAGgFAGgEIAMgHIANgEIAPgBIAOABIAOAEIAMAHQAGAEAFAFIAKALIAGANIAEAMIABAPIgBAOIgEAOIgGAMQgEAGgGAFQgFAGgGAEIgMAGIgOAEIgOABQgeAAgWgVgAIogQQgHAHgDAJQgEAIAAALQAAAKAEAKQADAJAHAHQAIAHAJADQAIAEALAAQAKAAAJgEQAJgDAHgHQAOgPAAgVQAAgLgDgIQgEgJgHgHQgHgHgJgEQgJgDgKAAQgVAAgPAOgAGyBZQgJgCgGgFQgHgEgFgHQgFgGgDgIIAUgMQACAGADAFQADAEAFADQAEADAFABQAGACAGAAIAMgBQAFgCADgCQADgCACgEQABgDAAgEQAAgFgBgDQgCgDgEgCQgHgFgRgFIgRgGIgNgHQgHgFgDgHQgDgGAAgJQAAgTANgLQAGgFAIgDQAIgDAKAAQAIAAAHACQAIACAGAEQAGAEAFAGQAFAGADAHIgTALIgFgIQgDgEgEgCQgDgDgFgBIgJgBIgJABQgFABgCACIgFAGIgBAHQAAAEABADIAFAFQALAFALAEIAWAIQAGACAEADQAHAGADAGIAEAIQABAEgBAFQAAAKgDAHQgDAIgHAFQgHAGgJADQgJACgLAAQgKAAgJgCgAB5BYQgKgDgHgHQgIgHgDgJQgEgIAAgMIAAhcIAXAAIAABbQAAAGACAGQACAFADADQAEAEAGACQAFACAIAAQAHAAAGgCQAGgCADgEQAEgDACgFQACgGAAgGIAAhbIAXAAIAABcQAAAMgEAIQgEAJgHAHQgHAHgKADQgJADgMAAQgMAAgJgDgAi9BGQgVgVAAgeQAAgIACgHQABgGACgGIAHgNIAJgLQAGgFAGgEIAMgHIANgEIAPgBIAOABIAOAEIAMAHQAGAEAFAFIAKALIAGANIAEAMIABAPIgBAOIgEAOIgGAMQgEAGgGAFQgFAGgGAEIgMAGIgOAEIgOABQgeAAgWgVgAitgQQgHAHgDAJQgEAIAAALQAAAKAEAKQADAJAHAHQAIAHAJADQAIAEALAAQAKAAAJgEQAJgDAHgHQAOgPAAgVQAAgLgDgIQgEgJgHgHQgHgHgJgEQgJgDgKAAQgVAAgPAOgAoNBYQgJgDgIgHQgHgHgEgJQgEgIAAgMIAAhcIAXAAIAABbQAAAGACAGQACAFAEADQAEAEAFACQAGACAHAAQAIAAAFgCQAGgCAEgEQAEgDACgFQABgGAAgGIAAhbIAXAAIAABcQAAAMgDAIQgEAJgHAHQgIAHgJADQgKADgMAAQgLAAgKgDgAt4BYQgJgDgIgHQgHgHgEgJQgEgIAAgMIAAhcIAXAAIAABbQAAAGACAGQACAFAEADQAEAEAFACQAGACAHAAQAIAAAFgCQAGgCAEgEQAEgDACgFQABgGAAgGIAAhbIAXAAIAABcQAAAMgDAIQgEAJgHAHQgIAHgJADQgKADgMAAQgLAAgKgDgAyqBaIgOgEIgMgGIgLgJQgGgGgDgGIgHgMQgDgGgBgHQgBgIAAgHQAAgIABgHQABgGADgHIAHgMQADgGAGgFQAFgFAGgEQAFgEAHgDIAOgEIAPgBQAJAAAJADQAJACAIAEQAIAEAGAHQAHAGAEAIIgUALIgHgJQgEgEgFgDQgFgDgGgCIgNgBQgLAAgJADQgJAEgHAHQgOAOAAAVQAAAWAOAOQAHAHAJADQAJAEALAAIANgCQAGgBAFgDQAFgDAEgEIAHgKIAUAMQgEAHgGAHQgHAGgIAEQgIAFgJACQgIACgKAAIgPgBgA7GBYQgKgDgHgHQgIgHgDgJQgEgIAAgMIAAhcIAXAAIAABbQAAAGACAGQACAFADADQAEAEAGACQAFACAIAAQAHAAAGgCQAGgCADgEQAEgDACgFQACgGAAgGIAAhbIAXAAIAABcQAAAMgEAIQgEAJgHAHQgHAHgKADQgJADgMAAQgMAAgJgDgAbeBZIhCheIAABeIgXAAIAAiLIASAAIBCBeIAAheIAXAAIAACLgAWQBZIAAg4IgxhTIAaAAIAiA9IAig9IAaAAIgwBTIAAA4gAU5BZIAAiLIAXAAIAACLgASaBZIgegzIgbAAIAAAzIgXAAIAAiLIA4AAQATAAANANQANANAAATQAAAFgCAHQgCAGgDAFQgEAGgFAEQgFAEgHACIAgA3gARhARIAhAAQAFAAAEgCQAEgBADgEQADgDABgEQACgDAAgFQAAgFgCgEQgBgFgDgDQgDgDgEgCQgEgCgFAAIghAAgAPhBZIAAiLIBUAAIAAAWIg9AAIAAAjIA4AAIAAAWIg4AAIAAAmIA+AAIAAAWgAOGBZIgxiLIAZAAIAmBvIAlhvIAZAAIgxCLgAMCBZIhCheIAABeIgXAAIAAiLIASAAIBCBeIAAheIAXAAIAACLgAE2BZIhCheIAABeIgXAAIAAiLIASAAIBCBeIAAheIAXAAIAACLgAAsBZIhBheIAABeIgXAAIAAiLIASAAIBBBeIAAheIAXAAIAACLgAj1BZIg3hDIAABDIgXAAIAAiLIAXAAIAAA+IA1g+IAbAAIg4BDIA6BIgAl2BZIAAiLIAXAAIAACLgAqMBZIAAiLIAXAAIAAB1IA5AAIAAAWgAq6BZIhCheIAABeIgXAAIAAiLIASAAIBCBeIAAheIAXAAIAACLgAvwBZIgKgcIg7AAIgKAcIgZAAIAziLIAbAAIAzCLgAwBAnIgXg+IgWA+IAtAAgA0FBZIgKgcIg7AAIgKAcIgZAAIAziLIAbAAIAzCLgA0WAnIgXg+IgWA+IAtAAgA23BZIAAg4IgxhTIAaAAIAjA9IAig9IAaAAIgxBTIAAA4gA4JBZIhCheIAABeIgXAAIAAiLIASAAIBCBeIAAheIAXAAIAACLgA90BZIAAiLIA3AAIAOABIANAEQAGACAFAEIAKAJQATAUAAAdQAAAdgTAVIgKAIQgFAEgGADQgGACgHABIgOACgA9dBDIAgAAQAKAAAIgEQAIgDAGgHQAHgHADgIQADgJAAgKQAAgLgDgIQgDgIgHgHQgGgGgIgEQgIgDgKAAIggAAgAnthBQgEgEAAgFQAAgFAEgDQADgEAFAAQAFAAAEAEQADADAAAFQAAAFgDAEQgEADgFAAQgFAAgDgDgAoThBQgEgEAAgFQAAgFAEgDQADgEAFAAQAFAAAEAEQADADAAAFQAAAFgDAEQgEADgFAAQgFAAgDgDgAtYhBQgEgEAAgFQAAgFAEgDQADgEAFAAQAFAAAEAEQADADAAAFQAAAFgDAEQgEADgFAAQgFAAgDgDgAt+hBQgEgEAAgFQAAgFAEgDQADgEAFAAQAFAAAEAEQADADAAAFQAAAFgDAEQgEADgFAAQgFAAgDgDgA6nhBQgDgEAAgFQAAgFADgDQAEgEAFAAQAFAAADAEQAEADAAAFQAAAFgEAEQgDADgFAAQgFAAgEgDgA7NhBQgDgEAAgFQAAgFADgDQAEgEAFAAQAFAAADAEQAEADAAAFQAAAFgEAEQgDADgFAAQgFAAgEgDgAU/g/QgEgCgCgDQgDgEAAgEQAAgFAFgFQAEgEAFAAQAFAAADADQAEACABAEQACAEgBAEQgBAEgDADQgDADgEABIgCAAIgGgBgAlwg/QgEgCgCgDQgDgEAAgEQAAgFAFgFQAEgEAFAAQAFAAADADQAEACABAEQACAEgBAEQgBAEgDADQgDADgEABIgCAAIgGgBg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-190.8,-9.1,381.8,18.2);


(lib.Tween20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AUwBYQgKgDgHgHQgIgHgDgJQgEgIAAgMIAAhcIAXAAIAABbQAAAGACAGQACAFADADQAEAEAGACQAFACAIAAQAHAAAGgCQAGgCADgEQAEgDACgFQACgGAAgGIAAhbIAXAAIAABcQAAAMgEAIQgEAJgHAHQgHAHgKADQgJADgMAAQgMAAgJgDgAQGBGQgVgVAAgeQAAgIABgHQABgGADgGIAHgNIAJgLQAFgFAGgEIAMgHIAOgEIAOgBIAPABIANAEIANAHQAGAEAFAFIAJALIAHANIAEAMIABAPIgBAOIgEAOIgHAMQgEAGgFAFQgFAGgGAEIgNAGIgNAEIgPABQgeAAgVgVgAQWgQQgHAHgEAJQgDAIAAALQAAAKADAKQAEAJAHAHQAHAHAJADQAJAEAKAAQALAAAJgEQAIgDAIgHQAOgPAAgVQAAgLgEgIQgDgJgHgHQgIgHgIgEQgJgDgLAAQgVAAgOAOgACxBYQgKgDgHgHQgIgHgDgJQgEgIAAgMIAAhcIAXAAIAABbQAAAGACAGQACAFADADQAEAEAGACQAFACAIAAQAHAAAGgCQAGgCADgEQAEgDACgFQACgGAAgGIAAhbIAXAAIAABcQAAAMgEAIQgEAJgHAHQgHAHgKADQgJADgMAAQgMAAgJgDgAApBaIgOgEIgMgGIgMgKQgUgVAAgeQAAgIACgHQABgGACgGIAHgNIAIgLQAGgFAGgEQAFgEAHgDIAOgEIAPgBQAJAAAKADQAJACAHAEQAIAFAHAGQAGAGAFAHIgUAMQgDgFgEgEQgEgEgGgDQgFgDgGgCIgNgBQgLAAgJADQgJAEgIAHQgHAHgDAJQgEAIAAALQAAALAEAJQADAJAHAHQAIAHAJADQAKAEALAAQAJAAAIgCQAIgDAFgEQAGgEAEgGQAEgGABgHIgvAAIAAgVIBGAAIAAAKIgBAOQgBAGgCAGIgGALQgEAGgFAEIgKAIQgFAEgGACQgHACgHABIgOABIgQgBgAkEBGQgVgVAAgeQAAgIABgHQABgGADgGIAHgNIAJgLQAFgFAGgEIAMgHIAOgEIAOgBIAPABIANAEIANAHQAGAEAFAFIAJALIAHANIAEAMIABAPIgBAOIgEAOIgHAMQgEAGgFAFQgFAGgGAEIgNAGIgNAEIgPABQgeAAgVgVgAj0gQQgHAHgEAJQgDAIAAALQAAAKADAKQAEAJAHAHQAHAHAJADQAJAEAKAAQALAAAJgEQAIgDAIgHQAOgPAAgVQAAgLgEgIQgDgJgHgHQgIgHgIgEQgJgDgLAAQgVAAgOAOgAbrBZIhCheIAABeIgXAAIAAiLIASAAIBCBeIAAheIAXAAIAACLgAZqBZIgKgcIg7AAIgKAcIgZAAIAziLIAbAAIAzCLgAZZAnIgXg+IgWA+IAtAAgAW4BZIAAg4IgxhTIAaAAIAjA9IAig9IAaAAIgxBTIAAA4gATnBZIgegzIgbAAIAAAzIgXAAIAAiLIA4AAQATAAANANQANANAAATQAAAFgCAHQgCAGgEAFQgEAGgFAEQgFAEgGACIAgA3gASuARIAhAAQAEAAAEgCQAEgBADgEQADgDACgEQACgDAAgFQAAgFgCgEQgCgFgDgDQgDgDgEgCQgEgCgEAAIghAAgAPNBZIg3hDIAABDIgXAAIAAiLIAXAAIAAA+IA1g+IAcAAIg5BDIA7BIgAMaBZIAAiLIAXAAIAACLgAKqBZIAAgTIA/hiIg9AAIAAgWIBaAAIAAATIg/BiIBAAAIAAAWgAKGBZIgegzIgbAAIAAAzIgXAAIAAiLIA4AAQATAAANANQANANAAATQAAAFgCAHQgCAGgDAFQgEAGgFAEQgFAEgHACIAgA3gAJNARIAhAAQAFAAAEgCQAEgBADgEQADgDABgEQACgDAAgFQAAgFgCgEQgBgFgDgDQgDgDgEgCQgEgCgFAAIghAAgAIOBZIgJgcIg8AAIgKAcIgZAAIAziLIAcAAIAyCLgAH9AnIgWg+IgWA+IAsAAgAFkBZIAAh1IgoAAIAAgWIBmAAIAAAWIgnAAIAAB1gAh6BZIAAgTIA/hiIg9AAIAAgWIBaAAIAAATIg/BiIBAAAIAAAWgAmuBZIAAiLIBUAAIAAAWIg9AAIAAAjIA4AAIAAAWIg4AAIAAAmIA+AAIAAAWgAncBZIhCheIAABeIgXAAIAAiLIASAAIBCBeIAAheIAXAAIAACLgApoBZIAAiLIAXAAIAACLgAr3BZIAAiLIA3AAIAOABIANAEQAGACAFAEIAKAJQATAUAAAdQAAAdgTAVIgKAIQgFAEgGADQgGACgHABIgOACgArgBDIAgAAQAKAAAIgEQAIgDAGgHQAHgHADgIQADgJAAgKQAAgLgDgIQgDgIgHgHQgGgGgIgEQgIgDgKAAIggAAgAslBZIhCheIAABeIgXAAIAAiLIASAAIBCBeIAAheIAXAAIAACLgAvnBZIAAiLIBUAAIAAAWIg9AAIAAAjIA4AAIAAAWIg4AAIAAAmIA+AAIAAAWgAwSBZIg3hDIAABDIgXAAIAAiLIAXAAIAAA+IA1g+IAcAAIg5BDIA7BIgAy6BZIgJgcIg8AAIgKAcIgZAAIAziLIAcAAIAyCLgAzLAnIgWg+IgWA+IAsAAgA1IBZIAAhjIgqBFIgDAAIgrhFIAABjIgXAAIAAiLIAZAAIAqBFIArhFIAYAAIAACLgA3qBZIAAiLIAXAAIAACLgA4SBZIgJgcIg8AAIgKAcIgZAAIAziLIAcAAIAyCLgA4jAnIgWg+IgWA+IAsAAgA78BZIAAiLIA3AAIAOABIANAEQAGACAFAEIAKAJQATAUAAAdQAAAdgTAVIgKAIQgFAEgGADQgGACgHABIgOACgA7lBDIAgAAQAKAAAIgEQAIgDAGgHQAHgHADgIQADgJAAgKQAAgLgDgIQgDgIgHgHQgGgGgIgEQgIgDgKAAIggAAgADQhBQgDgEAAgFQAAgFADgDQAEgEAFAAQAFAAADAEQAEADAAAFQAAAFgEAEQgDADgFAAQgFAAgEgDgACqhBQgDgEAAgFQAAgFADgDQAEgEAFAAQAFAAADAEQAEADAAAFQAAAFgEAEQgDADgFAAQgFAAgEgDgAphg/QgFgCgCgDQgCgEAAgEQAAgFAEgFQAEgEAGAAQAEAAAEADQADACACAEQABAEAAAEQgBAEgDADQgDADgEABIgDAAIgFgBgA3jg/QgFgCgCgDQgCgEAAgEQAAgFAEgFQAEgEAGAAQAEAAAEADQADACACAEQABAEAAAEQgBAEgDADQgDADgEABIgDAAIgFgBgAjGhCQgEgEAAgFQAAgFAEgDQADgEAFAAQAFAAAEAEQADADAAAFQAAAFgDAEQgEADgFAAQgFAAgDgDgAjshCQgEgEAAgFQAAgFAEgDQADgEAFAAQAFAAAEAEQADADAAAFQAAAFgDAEQgEADgFAAQgFAAgDgDg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-178.8,-9.1,357.8,18.2);


(lib.Tween19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AUwBYQgKgDgHgHQgIgHgDgJQgEgIAAgMIAAhcIAXAAIAABbQAAAGACAGQACAFADADQAEAEAGACQAFACAIAAQAHAAAGgCQAGgCADgEQAEgDACgFQACgGAAgGIAAhbIAXAAIAABcQAAAMgEAIQgEAJgHAHQgHAHgKADQgJADgMAAQgMAAgJgDgAQGBGQgVgVAAgeQAAgIABgHQABgGADgGIAHgNIAJgLQAFgFAGgEIAMgHIAOgEIAOgBIAPABIANAEIANAHQAGAEAFAFIAJALIAHANIAEAMIABAPIgBAOIgEAOIgHAMQgEAGgFAFQgFAGgGAEIgNAGIgNAEIgPABQgeAAgVgVgAQWgQQgHAHgEAJQgDAIAAALQAAAKADAKQAEAJAHAHQAHAHAJADQAJAEAKAAQALAAAJgEQAIgDAIgHQAOgPAAgVQAAgLgEgIQgDgJgHgHQgIgHgIgEQgJgDgLAAQgVAAgOAOgACxBYQgKgDgHgHQgIgHgDgJQgEgIAAgMIAAhcIAXAAIAABbQAAAGACAGQACAFADADQAEAEAGACQAFACAIAAQAHAAAGgCQAGgCADgEQAEgDACgFQACgGAAgGIAAhbIAXAAIAABcQAAAMgEAIQgEAJgHAHQgHAHgKADQgJADgMAAQgMAAgJgDgAApBaIgOgEIgMgGIgMgKQgUgVAAgeQAAgIACgHQABgGACgGIAHgNIAIgLQAGgFAGgEQAFgEAHgDIAOgEIAPgBQAJAAAKADQAJACAHAEQAIAFAHAGQAGAGAFAHIgUAMQgDgFgEgEQgEgEgGgDQgFgDgGgCIgNgBQgLAAgJADQgJAEgIAHQgHAHgDAJQgEAIAAALQAAALAEAJQADAJAHAHQAIAHAJADQAKAEALAAQAJAAAIgCQAIgDAFgEQAGgEAEgGQAEgGABgHIgvAAIAAgVIBGAAIAAAKIgBAOQgBAGgCAGIgGALQgEAGgFAEIgKAIQgFAEgGACQgHACgHABIgOABIgQgBgAkEBGQgVgVAAgeQAAgIABgHQABgGADgGIAHgNIAJgLQAFgFAGgEIAMgHIAOgEIAOgBIAPABIANAEIANAHQAGAEAFAFIAJALIAHANIAEAMIABAPIgBAOIgEAOIgHAMQgEAGgFAFQgFAGgGAEIgNAGIgNAEIgPABQgeAAgVgVgAj0gQQgHAHgEAJQgDAIAAALQAAAKADAKQAEAJAHAHQAHAHAJADQAJAEAKAAQALAAAJgEQAIgDAIgHQAOgPAAgVQAAgLgEgIQgDgJgHgHQgIgHgIgEQgJgDgLAAQgVAAgOAOgAbrBZIhCheIAABeIgXAAIAAiLIASAAIBCBeIAAheIAXAAIAACLgAZqBZIgKgcIg7AAIgKAcIgZAAIAziLIAbAAIAzCLgAZZAnIgXg+IgWA+IAtAAgAW4BZIAAg4IgxhTIAaAAIAjA9IAig9IAaAAIgxBTIAAA4gATnBZIgegzIgbAAIAAAzIgXAAIAAiLIA4AAQATAAANANQANANAAATQAAAFgCAHQgCAGgEAFQgEAGgFAEQgFAEgGACIAgA3gASuARIAhAAQAEAAAEgCQAEgBADgEQADgDACgEQACgDAAgFQAAgFgCgEQgCgFgDgDQgDgDgEgCQgEgCgEAAIghAAgAPNBZIg3hDIAABDIgXAAIAAiLIAXAAIAAA+IA1g+IAcAAIg5BDIA7BIgAMaBZIAAiLIAXAAIAACLgAKqBZIAAgTIA/hiIg9AAIAAgWIBaAAIAAATIg/BiIBAAAIAAAWgAKGBZIgegzIgbAAIAAAzIgXAAIAAiLIA4AAQATAAANANQANANAAATQAAAFgCAHQgCAGgDAFQgEAGgFAEQgFAEgHACIAgA3gAJNARIAhAAQAFAAAEgCQAEgBADgEQADgDABgEQACgDAAgFQAAgFgCgEQgBgFgDgDQgDgDgEgCQgEgCgFAAIghAAgAIOBZIgJgcIg8AAIgKAcIgZAAIAziLIAcAAIAyCLgAH9AnIgWg+IgWA+IAsAAgAFkBZIAAh1IgoAAIAAgWIBmAAIAAAWIgnAAIAAB1gAh6BZIAAgTIA/hiIg9AAIAAgWIBaAAIAAATIg/BiIBAAAIAAAWgAmuBZIAAiLIBUAAIAAAWIg9AAIAAAjIA4AAIAAAWIg4AAIAAAmIA+AAIAAAWgAncBZIhCheIAABeIgXAAIAAiLIASAAIBCBeIAAheIAXAAIAACLgApoBZIAAiLIAXAAIAACLgAr3BZIAAiLIA3AAIAOABIANAEQAGACAFAEIAKAJQATAUAAAdQAAAdgTAVIgKAIQgFAEgGADQgGACgHABIgOACgArgBDIAgAAQAKAAAIgEQAIgDAGgHQAHgHADgIQADgJAAgKQAAgLgDgIQgDgIgHgHQgGgGgIgEQgIgDgKAAIggAAgAslBZIhCheIAABeIgXAAIAAiLIASAAIBCBeIAAheIAXAAIAACLgAvnBZIAAiLIBUAAIAAAWIg9AAIAAAjIA4AAIAAAWIg4AAIAAAmIA+AAIAAAWgAwSBZIg3hDIAABDIgXAAIAAiLIAXAAIAAA+IA1g+IAcAAIg5BDIA7BIgAy6BZIgJgcIg8AAIgKAcIgZAAIAziLIAcAAIAyCLgAzLAnIgWg+IgWA+IAsAAgA1IBZIAAhjIgqBFIgDAAIgrhFIAABjIgXAAIAAiLIAZAAIAqBFIArhFIAYAAIAACLgA3qBZIAAiLIAXAAIAACLgA4SBZIgJgcIg8AAIgKAcIgZAAIAziLIAcAAIAyCLgA4jAnIgWg+IgWA+IAsAAgA78BZIAAiLIA3AAIAOABIANAEQAGACAFAEIAKAJQATAUAAAdQAAAdgTAVIgKAIQgFAEgGADQgGACgHABIgOACgA7lBDIAgAAQAKAAAIgEQAIgDAGgHQAHgHADgIQADgJAAgKQAAgLgDgIQgDgIgHgHQgGgGgIgEQgIgDgKAAIggAAgADQhBQgDgEAAgFQAAgFADgDQAEgEAFAAQAFAAADAEQAEADAAAFQAAAFgEAEQgDADgFAAQgFAAgEgDgACqhBQgDgEAAgFQAAgFADgDQAEgEAFAAQAFAAADAEQAEADAAAFQAAAFgEAEQgDADgFAAQgFAAgEgDgAphg/QgFgCgCgDQgCgEAAgEQAAgFAEgFQAEgEAGAAQAEAAAEADQADACACAEQABAEAAAEQgBAEgDADQgDADgEABIgDAAIgFgBgA3jg/QgFgCgCgDQgCgEAAgEQAAgFAEgFQAEgEAGAAQAEAAAEADQADACACAEQABAEAAAEQgBAEgDADQgDADgEABIgDAAIgFgBgAjGhCQgEgEAAgFQAAgFAEgDQADgEAFAAQAFAAAEAEQADADAAAFQAAAFgDAEQgEADgFAAQgFAAgDgDgAjshCQgEgEAAgFQAAgFAEgDQADgEAFAAQAFAAAEAEQADADAAAFQAAAFgDAEQgEADgFAAQgFAAgDgDg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-178.8,-9.1,357.8,18.2);


(lib.Tween14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#747F8B").s().p("AR3gEIAAB2IgcAAIAAjJIBgB6IAAhzIAdAAIAADIgAwbgEIAAB2IgcAAIAAjJIBgB6IAAhzIAdAAIAADIgAlxBwQgKgEgJgIQgIgIgEgLQgFgLAAgMIAAhTQAAgMAFgLQAFgLAHgIQAJgIAKgFQALgEAMAAQANAAALAEQAKAFAJAIQAIAIAEAKQAFALAAANIAABSQAAAMgFALQgEALgIAIQgJAIgKAFQgLAFgNAAQgMAAgLgFgAllg3QgFACgEAFQgEAEgDAFQgCAGAAAGIAABWQAAAMAIAJQAEAEAFADQAGACAGAAQAFAAAGgCQAFgDAEgEQAFgEACgGQADgFgBgGIAAhWQAAgMgIgJQgEgFgFgCQgGgDgGAAQgFAAgGADgAofBwQgKgEgIgIQgJgIgDgLQgGgLAAgMIAAhTQAAgMAGgLQAEgLAIgIQAIgIALgFQALgEAMAAQAMAAALAEQALAFAIAIQAJAIAEAKQAFALgBANIAABSQABAMgFALQgEALgJAIQgIAIgLAFQgLAFgMAAQgNAAgLgFgAoTg3QgFACgEAFQgEAEgCAFQgCAGgBAGIAABWQABAMAHAJQAFAEAEADQAGACAGAAQAGAAAGgCQAFgDAEgEQAEgEADgGQACgFAAgGIAAhWQAAgMgJgJQgEgFgFgCQgFgDgGAAQgGAAgGADgArnBnIAAgoQAEAHAIAHQAHAFAJADQAKAEAMAAQAIAAAHgDQAIgDAGgGQAFgFADgIQADgHAAgIQAAgJgCgHQgEgIgEgGQgGgFgHgDQgHgEgIAAQgNAAgLAGQgMAGgIALIAAhuIBbAAIAAAbIg/AAIAAAlQAGgDAMAAQAQAAANAFQAMAFAIAJQAJAKAEAMQAEANAAANQAAAOgFANQgGAMgJAKQgLAJgMAFQgNAGgNAAQgnAAgMgOgAOzByQgKgCgJgDQgJgEgIgGIgPgMIgMgPQgFgIgEgJQgFgJgBgKQgCgKAAgKQAAgKACgJQABgKAFgJQAEgJAFgIIAMgPQAHgHAIgFQAIgGAJgDQAJgEAKgCQAKgDAKAAQAKAAAKADQAKACAJAEQAJADAIAGQAIAFAHAHQAHAHAFAIQAFAIAEAJQAFAJACAKQABAJAAAKQAAAKgBAKQgCAKgFAJQgEAJgFAIQgFAIgHAHIgPAMQgIAGgJAEQgJADgKACQgKACgKAAQgKAAgKgCgAOsgzQgMAFgKAKQgKAKgEANQgFANgBAQQABAQAGAOQAFANALAKQAKAKAMAFQANAFAMAAQANAAANgFQAMgFAIgKQALgKAFgNQAGgOAAgQQAAgQgGgNQgFgNgKgKQgJgKgMgFQgOgFgNAAQgPAAgMAFgABNByQgKgCgJgDQgJgEgIgGIgPgMIgMgPQgGgIgDgJQgEgJgBgKQgCgKAAgKQAAgKACgJQABgKAEgJQADgJAGgIIAMgPQAHgHAIgFQAIgGAJgDQAJgEAKgCQAKgDAKAAQALAAAKADQAJACAJAEQAJADAIAGQAIAFAHAHQAHAHAFAIQAFAIAFAJQAEAJABAKQACAJAAAKQAAAKgCAKQgBAKgEAJQgFAJgFAIQgFAIgHAHIgPAMQgIAGgJAEQgJADgJACQgKACgLAAQgKAAgKgCgABGgzQgMAFgKAKQgJAKgGANQgEANAAAQQAAAQAFAOQAGANAKAKQALAKAMAFQAMAFANAAQANAAAMgFQAMgFAKgKQAJgKAGgNQAFgOABgQQgBgQgFgNQgFgNgJgKQgKgKgNgFQgNgFgNAAQgOAAgNAFgAhyBtQgXgLgJgIQgHgHgGgIQgGgIgEgJQgEgJgCgLQgCgKAAgMQAAgLACgJQABgKAEgJQAEgJAFgIQAFgIAHgHQAHgHAIgFQAJgFAIgEQAKgEALgBQAKgDALAAQAOAAAYAJIAAAgQgHgGgMgDQgKgEgJAAQgOAAgNAFQgNAGgJAJQgKAKgGANQgGANAAAQQAAARAGAOQAGANAKAJQAKAKAMAFQANAFANAAQANAAAJgDQAJgDAMgHIAAAgQgIAFgNACQgLABgOAAQgYgCgLgFgAUWByIAAjDIBVAAIAAAaIg2AAIAABPIA2AAIAAAaIg2AAIAAAmIA5AAIAAAagAMVByIAAjCIAfAAIAADCgAJyByIBDioIg4AAIAAgaIBkAAIhECnIBBAAIAAAbgAHuByIAAjDIBWAAIAAAaIg3AAIAABPIA3AAIAAAaIg3AAIAAAmIA6AAIAAAagAFyByIAAjCIAeAAIAACoIA1AAIAAAagAD1ByIAAjCIAeAAIAACoIA1AAIAAAagAt8ByIAAjCIAfAAIAADCgAzHByIAAjDIBVAAIAAAaIg2AAIAABPIA2AAIAAAaIg2AAIAAAmIA5AAIAAAagA1BByIAAhIIgth6IAiAAIAcBWIAdhWIAfAAIguB5IAABJgAt5hdIAAgaIAaAAIAAAag");
	this.shape.setTransform(-0.4,-40.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-269.5,-56.7,539.1,113.5);


(lib.Tween6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.FlashAICB_2();
	this.instance.parent = this;
	this.instance.setTransform(-323.5,-439.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-323.5,-439.5,647,879);


(lib.Tween4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.FlashAICB();
	this.instance.parent = this;
	this.instance.setTransform(-323.5,-439.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-323.5,-439.5,647,879);


(lib.Tween2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.FlashAICB_1();
	this.instance.parent = this;
	this.instance.setTransform(-111.5,-24);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-111.5,-24,223,48);


(lib.Symbol7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgaALIAAgUIA0gBIABAVgAgYAJIAxAAIAAgRIgxAAg");
	this.shape.setTransform(57.6,16.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgZAKIAAgTIAzAAIAAATg");
	this.shape_1.setTransform(57.5,16.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgiAXIAAgsQAAgjAiAAQAiAAAAAfIAAALIgaAAIAAgIQAAgNgIAAIAAAAQgHAAAAAKIgBA0QAAAJAIAAQAIAAAAgOIAAgLIAbAAIAAAOQAAAggkAAQghAAAAgigAghgVIAAAsQAAAhAgAAQAjAAAAgfIAAgNIgYAAIAAAKQAAAQgKAAQgJAAAAgLIAAg0QAAgMAJAAIAAAAQAJAAAAAPIAAAGIAYAAIAAgJQAAgdghAAQghAAAAAhg");
	this.shape_2.setTransform(57.6,9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgiAWIAAgsQAAghAiAAQAigCAAAgIAAAKIgZAAIAAgHQAAgOgJAAQgJAAAAALIAAA0QABAKAIAAQAJgBAAgPIAAgKIAaAAIAAAOQAAAfgkAAQggAAgBgig");
	this.shape_3.setTransform(57.6,9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgSAkQgHgHAAgPIAAgfQAAgYAZAAQAaAAAAAYIAAAfQAAAPgGAGQgGAHgNAAIgBAAQgMAAgGgGgAgYgRIAAAfQAAAbAZAAQANAAAFgGQAGgHAAgOIAAgfQAAgXgZAAQgXAAgBAXgAgGAQIAAggQAAgLAGAAQAHAAAAALIABAgQgBAMgGAAQgHAAAAgMgAgFgQIAAAgQAAALAGAAQAFAAAAgLIAAggQAAgKgGAAQgFAAAAAKg");
	this.shape_4.setTransform(49.4,9,1.354,1.354);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgaAvQgHgJAAgTIAAgrQgBgfAiAAQAiAAAAAfIAAArQAAATgHAJQgIAJgSAAQgSAAgJgJgAgIgWIAAArQAAAQAJAAQAIAAAAgQIAAgrQAAgOgJAAQgIAAAAAOg");
	this.shape_5.setTransform(49.4,9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAKBJIgBgBIgOgvIgFALIAAAlIggAAIAAiRIAfAAIAAA2IAUg2IAgAAIgbBBIAdBQgAALBHIAcgBIgbhNIAag/IgcAAIgUA6IgDAAIAAg6IgbAAIAACNIAcAAIAAgjIAHgRg");
	this.shape_6.setTransform(41.5,7.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AALBIIgPgyIgHAOIAAAkIgdAAIgBiOIAeAAIAAA5IAUg6IAfAAIgbBAIAdBPg");
	this.shape_7.setTransform(41.4,7.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgTAIIAAgPIAmAAIABAPgAgSAHIAkAAIAAgNIgkAAg");
	this.shape_8.setTransform(57.6,16.5,1.354,1.354);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgSAHIAAgNIAlAAIAAANg");
	this.shape_9.setTransform(57.5,16.5,1.354,1.354);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgZARIAAggQAAgaAZAAQAaAAAAAXIAAAIIgUAAIAAgGQAAgKgGAAIAAAAQgFAAAAAIIgBAmQAAAHAGAAQAGAAAAgLIAAgIIAUAAIAAALQAAAXgaAAQgZAAAAgZgAgYgPIAAAgQAAAYAYAAQAZAAAAgWIAAgKIgRAAIAAAHQgBAMgHAAQgHAAAAgIIAAgmQAAgJAHAAIAAAAQAHAAAAALIAAAFIASAAIAAgHQAAgWgZAAQgYAAAAAZg");
	this.shape_10.setTransform(57.6,9,1.354,1.354);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgZARIAAggQAAgZAZAAQAZgBAAAXIAAAHIgSAAIAAgFQAAgKgHAAQgGAAAAAIIAAAmQAAAIAGAAQAGgBABgLIAAgHIATAAIAAAKQAAAXgaAAQgZAAAAgZg");
	this.shape_11.setTransform(57.6,9,1.354,1.354);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgSAkQgHgHAAgPIAAgfQAAgYAZAAQAaAAAAAYIAAAfQAAAPgGAGQgGAHgNAAIgBAAQgMAAgGgGgAgYgRIAAAfQAAAbAZAAQANAAAFgGQAGgHAAgOIAAgfQAAgXgZAAQgXAAgBAXgAgGAQIAAggQAAgLAGAAQAHAAAAALIABAgQgBAMgGAAQgHAAAAgMgAgFgQIAAAgQAAALAGAAQAFAAAAgLIAAggQAAgKgGAAQgFAAAAAKg");
	this.shape_12.setTransform(49.4,9,1.354,1.354);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgTAjQgFgHAAgOIAAgfQgBgYAZABQAZgBAAAYIAAAfQAAAOgFAHQgGAGgOAAQgNAAgGgGgAgGgPIAAAfQAAALAGAAQAGAAAAgLIAAgfQAAgMgGAAQgGAAAAAMg");
	this.shape_13.setTransform(49.4,9,1.354,1.354);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAHA2IAAgBIgLgjIgDAJIAAAbIgYAAIAAhrIAXAAIAAAoIAOgoIAYAAIgUAwIAWA7gAAIA0IAVAAIgUg5IATguIgVAAIgOAqIgCAAIAAgqIgUAAIAABnIAUAAIAAgaIAGgMg");
	this.shape_14.setTransform(41.5,7.3,1.354,1.354);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAIA1IgLglIgFALIAAAaIgVAAIgBhoIAWAAIAAApIAPgqIAXAAIgVAvIAWA6g");
	this.shape_15.setTransform(41.4,7.3,1.354,1.354);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAkAoQgEgWgEgNQgJgZgSABQgOABAAAOQABAEAEADQAEADAEAAQAEAAAEgEQAEgDgCgGQADABADAEQAFAGAAALQgFAXgUAGQgQAFgMgEQgfgMAAglQAAgdATgQQAQgOAbgBQAbgCAVASQARAOAAAJIAAAVIgMAAQgDgLgIgLQgRgWgaABIgVAGQgVALABAaQAAAYAVAHQAUAHAIgRQgJAHgNgEQgQgFgCgSQAAgeAegDIAKAAQAQACAKANIAGAJQAGAKACAJQAEAUACAHQAFAOAHAAIAAARIgBAAQgRAAgKgZg");
	this.shape_16.setTransform(8.6,9,1.354,1.354);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AhXBZIAAgYIABAAQAKgBAGgSQAEgLAEgYIAAgCQADgMAIgNIAIgNQALgRAZgDIANgBQArAEgBAqQgEAiggAAQgKAAgIgFQAIANARAAQAQAAALgMQANgNABgTQABgigdgPIgcgJIgCAAQgiAAgWAeQgKAOgEAPIgBAAIgEABIgNAAIAAgdQAAgMAWgTQAbgYAkAAIADAAQAlABAXAUQAaAWAAAnQgBAygqARQgHADgLAAQgugBgJgqQAAgPAGgJQAFgHAEgBIABAAIAAABQgCAGADAFQAFAHAIAAQAPgCABgMQABgKgHgFQgFgEgHAAQgUgBgLAXQgGALgGAfIgFAQQgMAjgZgBgAgHgwQgXADgMARIgIAMQgIAOgCAMIAAABQgEAZgEALQgHASgKACIAAAVIAAAAQAZAAALgiIAEgQQAGgeAHgMQAMgYAUACQAIAAAFAEQAHAGgBAKQAAAGgGAFQgFAEgGABQgJAAgFgIQgEgGACgFQgNAIABAWQAIApAtAAQAKAAAHgDQAqgQAAgxQAAgkgWgWQgWgVgogBIgDgBQglAAgaAYQgVAUAAAKIAAAbIAPAAQAEgQANgRQAWgbAjABIAdAIQAdAQgBAjQAAAUgOAOQgMALgQAAQgTAAgIgQIABAAQAIAGALAAQAgAAACghQACgqgqgCIgBgBg");
	this.shape_17.setTransform(26,9);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AhWBZIAAgXQALgBAGgTQAEgLAEgZQADgMAIgOIAIgMQALgRAZgDQAEgCAJACQATABALALQALALgBAVQgCAZgVAHQgRAFgOgJQAMAWAbgJQAcgKABghQABgjgdgPIgcgIQgkgBgXAeQgLAPgEAPIgQAAIAAgcQAAgMAWgTQAcgaAmADQAkACAXATQAZAVAAAnQAAAygqAQQgQAHgVgHQgdgIgGgfQAAgPAGgIQAEgHAFgBQgDAIAGAGQAFAFAHAAQAFgBAFgEQAGgEAAgGQABgJgHgFQgFgFgIAAQgXgCgMAiQgHASgGAeQgLAigZAAIgCAAg");
	this.shape_18.setTransform(25.9,8.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol7, new cjs.Rectangle(0,0,61.2,17.9), null);


(lib.ClipGroup = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Image();
	this.instance.parent = this;
	this.instance.setTransform(0,0,1.08,1.081);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.ClipGroup, new cjs.Rectangle(0,0,108,103.8), null);


(lib.cta = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Livello_2 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AGNBHIgMgDIgKgFIgJgHIgHgJIgFgKIgDgLIgBgMIABgLIADgKIAFgKIAHgJIAJgHIAKgGIALgDIANgBQAHAAAHACQAHACAHAEQAHADAFAFQAFAFADAGIgNAIIgGgJIgIgGQgFgDgFgBQgGgBgGAAQgMABgFACIgIAEIgGAFQgGAGgDAIQgDAHAAAJQAAAJADAIQADAIAGAGQAMANAUAAQAIAAAHgCQAHgCAFgEQAFgEAEgGQADgFABgHIgpAAIAAgNIA4AAIAAAGIgBALIgDAKIgFAIIgGAIQgPAOgZAAIgMgBgAHiBGIAAhvIAPAAIAABvgAEWBGIAAhvIAPAAIAABhIAwAAIAAAOgADvBGIAAhvIAPAAIAABvgACNBGIAAhvIAtAAQAHAAAFACQAGADAEAEQAFAFACAFQACAFAAAHQAAAHgDAFQgDAGgGAEIAHAFIAFAGQADADABAEQABAEAAAFQAAAGgCAGQgDAGgEAEQgKAJgNAAgACcA4IAiAAIAHgBQADgBACgDQADgCABgEIABgHIgBgHIgEgGQgFgFgHAAIgiAAgACcAGIAeAAIAHgBIAFgEQACgBABgDIACgHQAAgDgCgDQgBgDgCgDIgGgEIgGgBIgeAAgAA/BGIAAhvIAPAAIAABvgAgOBGIAAhvIAOAAIAABhIAwAAIAAAOgAhSBGIAAgtIgnhCIAQAAIAfA0IAeg0IARAAIgoBCIAAAtgAiLBGIgKgZIgyAAIgJAZIgQAAIAqhvIARAAIApBvgAiaAfIgUg2IgUA2IAoAAgAkTBGIAAhhIghAAIAAgOIBQAAIAAAOIghAAIAABhgAmABGIAAhvIBCAAIAAAOIgzAAIAAAiIAvAAIAAAOIgvAAIAAAjIA0AAIAAAOgAnyBGIAAhvIArAAQAXAAAPARIAHAIIAFAKIADAJIABALIgBAMIgDAKIgFAJQgDAFgEAEIgIAHIgJAFIgKADIgLABgAnjA4IAcAAQAJAAAHgDQAHgDAFgGQAGgGADgHQACgIAAgJQAAgJgCgGQgDgIgGgGQgFgGgHgDQgHgDgJAAIgcAAgAHig2QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgADvg2QgCgDAAgEQAAgEACgDQADgDAFAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgFAAgDgDg");
	this.shape.setTransform(84.9,13.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Livello_1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#4DC6D4").s().p("AtRCCIAAkDIajAAIAAEDg");
	this.shape_1.setTransform(85,14.8);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.cta, new cjs.Rectangle(-5.5,1.8,180.5,49.1), null);


// stage content:
(lib.index = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_209 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(209).call(this.frame_209).wait(1));

	// cta
	this.instance = new lib.cta();
	this.instance.parent = this;
	this.instance.setTransform(821.2,183.1,1.117,1.117,0,0,0,85.1,16.1);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(197).to({_off:false},0).to({y:168.4,alpha:1},12).wait(1));

	// Layer 2
	this.instance_1 = new lib.Tween21("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(821.6,137,1.006,1.006);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.instance_2 = new lib.Tween22("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(821.6,137,1.006,1.006);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(147).to({_off:false},0).to({_off:true,alpha:1},12).wait(51));
	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(147).to({_off:false},12).wait(38).to({startPosition:0},0).to({regX:0.1,regY:0.1,x:821.7,y:127},12).wait(1));

	// Layer 1
	this.instance_3 = new lib.Tween19("synched",0);
	this.instance_3.parent = this;
	this.instance_3.setTransform(821,107.8,1.006,1.006,0,0,0,0,0.1);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.instance_4 = new lib.Tween20("synched",0);
	this.instance_4.parent = this;
	this.instance_4.setTransform(821,107.8,1.006,1.006,0,0,0,0,0.1);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(132).to({_off:false},0).to({_off:true,alpha:1},12).wait(66));
	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(132).to({_off:false},12).wait(53).to({startPosition:0},0).to({y:97.8},12).wait(1));

	// Layer 11
	this.instance_5 = new lib.Tween14("synched",0);
	this.instance_5.parent = this;
	this.instance_5.setTransform(819.7,115.8,1.11,1.11,0,0,0,0.1,0);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(115).to({_off:false},0).to({alpha:1},13).wait(69).to({startPosition:0},0).to({regY:0.1,y:105.8},12).wait(1));

	// msk (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_15 = new cjs.Graphics().p("AC2NeIAAo/MAxkAAAIAAI/g");
	var mask_graphics_16 = new cjs.Graphics().p("AFvNeIAAo/MAxlAAAIAAI/g");
	var mask_graphics_17 = new cjs.Graphics().p("AIdNeIAAo/MAxkAAAIAAI/g");
	var mask_graphics_18 = new cjs.Graphics().p("AK+NeIAAo/MAxlAAAIAAI/g");
	var mask_graphics_19 = new cjs.Graphics().p("ANUNeIAAo/MAxlAAAIAAI/g");
	var mask_graphics_20 = new cjs.Graphics().p("APeNeIAAo/MAxkAAAIAAI/g");
	var mask_graphics_21 = new cjs.Graphics().p("ARbNeIAAo/MAxlAAAIAAI/g");
	var mask_graphics_22 = new cjs.Graphics().p("ATNNeIAAo/MAxlAAAIAAI/g");
	var mask_graphics_23 = new cjs.Graphics().p("AUzNeIAAo/MAxlAAAIAAI/g");
	var mask_graphics_24 = new cjs.Graphics().p("AWNNeIAAo/MAxkAAAIAAI/g");
	var mask_graphics_25 = new cjs.Graphics().p("AXbNeIAAo/MAxkAAAIAAI/g");
	var mask_graphics_26 = new cjs.Graphics().p("AYcNeIAAo/MAxlAAAIAAI/g");
	var mask_graphics_27 = new cjs.Graphics().p("AZSNeIAAo/MAxlAAAIAAI/g");
	var mask_graphics_28 = new cjs.Graphics().p("AZ8NeIAAo/MAxlAAAIAAI/g");
	var mask_graphics_29 = new cjs.Graphics().p("AaaNeIAAo/MAxlAAAIAAI/g");
	var mask_graphics_30 = new cjs.Graphics().p("AasNeIAAo/MAxlAAAIAAI/g");
	var mask_graphics_31 = new cjs.Graphics().p("AayNeIAAo/MAxlAAAIAAI/g");
	var mask_graphics_97 = new cjs.Graphics().p("AayNeIAAo/MAxlAAAIAAI/g");
	var mask_graphics_98 = new cjs.Graphics().p("AayNeIAAo/MAxlAAAIAAI/g");
	var mask_graphics_99 = new cjs.Graphics().p("AayNeIAAo/MAxlAAAIAAI/g");
	var mask_graphics_100 = new cjs.Graphics().p("AayNeIAAo/MAxlAAAIAAI/g");
	var mask_graphics_101 = new cjs.Graphics().p("AayNeIAAo/MAxlAAAIAAI/g");
	var mask_graphics_102 = new cjs.Graphics().p("AayNeIAAo/MAxlAAAIAAI/g");
	var mask_graphics_103 = new cjs.Graphics().p("AayNeIAAo/MAxlAAAIAAI/g");
	var mask_graphics_104 = new cjs.Graphics().p("AayNeIAAo/MAxlAAAIAAI/g");
	var mask_graphics_105 = new cjs.Graphics().p("AayNeIAAo/MAxlAAAIAAI/g");
	var mask_graphics_106 = new cjs.Graphics().p("AayNeIAAo/MAxlAAAIAAI/g");
	var mask_graphics_107 = new cjs.Graphics().p("AayNeIAAo/MAxlAAAIAAI/g");
	var mask_graphics_108 = new cjs.Graphics().p("AayNeIAAo/MAxlAAAIAAI/g");
	var mask_graphics_109 = new cjs.Graphics().p("AayNeIAAo/MAxlAAAIAAI/g");
	var mask_graphics_110 = new cjs.Graphics().p("AayNeIAAo/MAxlAAAIAAI/g");
	var mask_graphics_111 = new cjs.Graphics().p("AayNeIAAo/MAxlAAAIAAI/g");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(15).to({graphics:mask_graphics_15,x:335.4,y:86.2}).wait(1).to({graphics:mask_graphics_16,x:354,y:86.2}).wait(1).to({graphics:mask_graphics_17,x:371.3,y:86.2}).wait(1).to({graphics:mask_graphics_18,x:387.5,y:86.2}).wait(1).to({graphics:mask_graphics_19,x:402.5,y:86.2}).wait(1).to({graphics:mask_graphics_20,x:416.2,y:86.2}).wait(1).to({graphics:mask_graphics_21,x:428.8,y:86.2}).wait(1).to({graphics:mask_graphics_22,x:440.2,y:86.2}).wait(1).to({graphics:mask_graphics_23,x:450.4,y:86.2}).wait(1).to({graphics:mask_graphics_24,x:459.3,y:86.2}).wait(1).to({graphics:mask_graphics_25,x:467.1,y:86.2}).wait(1).to({graphics:mask_graphics_26,x:473.7,y:86.2}).wait(1).to({graphics:mask_graphics_27,x:479.1,y:86.2}).wait(1).to({graphics:mask_graphics_28,x:483.3,y:86.2}).wait(1).to({graphics:mask_graphics_29,x:486.3,y:86.2}).wait(1).to({graphics:mask_graphics_30,x:488.1,y:86.2}).wait(1).to({graphics:mask_graphics_31,x:488.7,y:86.2}).wait(66).to({graphics:mask_graphics_97,x:488.7,y:86.2}).wait(1).to({graphics:mask_graphics_98,x:488.7,y:86.2}).wait(1).to({graphics:mask_graphics_99,x:488.7,y:86.2}).wait(1).to({graphics:mask_graphics_100,x:488.7,y:86.2}).wait(1).to({graphics:mask_graphics_101,x:488.7,y:86.2}).wait(1).to({graphics:mask_graphics_102,x:488.7,y:86.2}).wait(1).to({graphics:mask_graphics_103,x:488.7,y:86.2}).wait(1).to({graphics:mask_graphics_104,x:488.7,y:86.2}).wait(1).to({graphics:mask_graphics_105,x:488.7,y:86.2}).wait(1).to({graphics:mask_graphics_106,x:488.7,y:86.2}).wait(1).to({graphics:mask_graphics_107,x:488.7,y:86.2}).wait(1).to({graphics:mask_graphics_108,x:488.7,y:86.2}).wait(1).to({graphics:mask_graphics_109,x:488.7,y:86.2}).wait(1).to({graphics:mask_graphics_110,x:488.7,y:86.2}).wait(1).to({graphics:mask_graphics_111,x:488.7,y:86.2}).wait(99));

	// Layer 7
	this.instance_6 = new lib.Tween6("synched",0);
	this.instance_6.parent = this;
	this.instance_6.setTransform(790.8,334.6,0.766,0.766,0,0,0,0.1,0.1);
	this.instance_6._off = true;

	var maskedShapeInstanceList = [this.instance_6];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(15).to({_off:false},0).wait(82).to({startPosition:0},0).to({alpha:0},14).wait(99));

	// Layer 5
	this.instance_7 = new lib.Tween2("synched",0);
	this.instance_7.parent = this;
	this.instance_7.setTransform(787.6,79,0.766,0.766);
	this.instance_7.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).to({x:810.6,alpha:1},12).wait(84).to({startPosition:0},0).to({alpha:0},14).wait(100));

	// Layer 4
	this.instance_8 = new lib.Tween4("synched",0);
	this.instance_8.parent = this;
	this.instance_8.setTransform(770.8,333,0.766,0.766,0,0,0,0.1,0.1);
	this.instance_8.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).to({x:793.8,alpha:1},12).wait(84).to({startPosition:0},0).to({alpha:0},14).wait(100));

	// logo
	this.instance_9 = new lib.Symbol7();
	this.instance_9.parent = this;
	this.instance_9.setTransform(40.4,204.6,0.961,0.952,0,0,0,30.8,9.4);

	this.instance_10 = new lib.ClipGroup();
	this.instance_10.parent = this;
	this.instance_10.setTransform(1168.3,190.8,0.564,0.563,0,0,0,54.5,52.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_10},{t:this.instance_9}]}).wait(210));

	// bg
	this.instance_11 = new lib.bbg();
	this.instance_11.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(210));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(602,108.2,1204,673.4);
// library properties:
lib.properties = {
	width: 1204,
	height: 224,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/index_atlas_.png?1528460873053", id:"index_atlas_"}
	],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;